org: yousefs
service: QuizTopia-Api-Yousef

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1

  iam:
    role: arn:aws:iam::396913740002:role/lecture-role


  environment:
    USERS_TABLE: Quizotopia-UserTable
    QUIZ_TABLE: Quizotopia-QuizTable2
    QUESTIONS_TABLE: Quizotopia-QuestionsTable
    LEADERBOARD_TABLE: Quizotopia-leaderboardTable
    JWT_KEY: ${env:JWT_KEY}

package:
  individually: true

functions:
  Signup:
    handler: functions/Account/Signup/index.handler
    events:
      - http:
          path: /auth/signup
          method: post

  Login:
    handler: functions/Account/Login/index.handler
    events:
      - http:
          path: /auth/login
          method: post

  CreateQuiz:
    handler: functions/Quiz/CreateQuiz/index.handler
    events:
      - httpApi:
          path: /quiz
          method: post

resources:
  Resources:

    QuestionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Quizotopia-QuestionsTable
        AttributeDefinitions:
          - AttributeName: questionId
            AttributeType: S
          - AttributeName: quizId
            AttributeType: S
        KeySchema:
          - AttributeName: questionId
            KeyType: HASH
          - AttributeName: quizId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: QuizIdIndex
            KeySchema:
              - AttributeName: quizId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Quizotopia-UserTable
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: UserId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: Username-Index
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    QuizTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Quizotopia-QuizTable2
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
          - AttributeName: UserId
            AttributeType: S
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
          - AttributeName: UserId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    LeaderboardTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Quizotopia-LeaderboardTable
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
          - AttributeName: UserId
            AttributeType: S
          - AttributeName: score
            AttributeType: N
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
          - AttributeName: UserId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: QuizScoreIndex
            KeySchema:
              - AttributeName: quizId
                KeyType: HASH
              - AttributeName: score
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
